### ISSUE TITLE
Can't view devices after enabling Notifications

### ISSUE THREAD

**Issue by ghost** [krlaframboise/SmartThings#1]
Once I turn on notifications for battery level I can no longer view the list of devices.  This error shows up in the live log.  

groovy.lang.MissingMethodException: No signature of method: physicalgraph.app.ContactProfileWrapper.hasCapability() is applicable for argument types: (java.lang.String) values: [Battery] @ line 385

**Comment by krlaframboise** [comment]
Fixed in version 1.4.4
