### ISSUE TITLE
GoControl Motion Sensor 0 degrees Temp

### ISSUE THREAD

**Issue by jmserranos** [krlaframboise/SmartThings#11]
Gocontrol Motion Sensor is reporting 0 degrees after updating to latest Device Handler (version 1.3.2) @krlaframboise

**Comment by krlaframboise** [comment]
I'm not seeing this problem and SmartThings was performing an update this afternoon so I'm not sure if that could have something to do with it.

Go into the device settings from the mobile app and tap Done.  Then open the cover of the device, wait about 10 seconds, and close it.  

Go back to the main Things tab in the mobile app, wait about 1 minute, open the device, and let me know if the temperature is back.
