### ISSUE TITLE
[Request] How to make power consumption table

### ISSUE THREAD

**Issue by AeonSaber** [krlaframboise/SmartThings#12]
I'm hoping you can assist me in creating a pivot table, or chart (excel or google sheets) to calculate my KWH per day/month. I can then multiple it by my power cost ~.086.

Right now I am logging my power every 5 minutes.

**Comment by krlaframboise** [comment]
If this request is regarding the Simple Event Logger SmartApp, please post the question to the topic on the SmartThings forum.  I think other users are already doing what you're trying to so they might be able to provide an answer faster than I can.  https://community.smartthings.com/t/release-simple-event-logger/69879
