### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by kansablankie** [krlaframboise/SmartThings#14]
HI

I get this error when I paste the code

No signature of method: script1498234467904925651483.metadata() is applicable for argument types: (script1498234467904925651483$_run_closure1) values: [script1498234467904925651483$_run_closure1@3b9a0ec5] Possible solutions: getMetadata(), getState(), setState(java.lang.Object), metaClass(groovy.lang.Closure)

No signature of method: script14982345943621299976176.metadata() is applicable for argument types: (script14982345943621299976176$_run_closure1) values: [script14982345943621299976176$_run_closure1@559621e7] Possible solutions: getMetadata(), getState(), setState(java.lang.Object), metaClass(groovy.lang.Closure)

No signature of method: script14982347167072094798852.metadata() is applicable for argument types: (script14982347167072094798852$_run_closure1) values: [script14982347167072094798852$_run_closure1@5cf8d882] Possible solutions: getMetadata(), getState(), setState(java.lang.Object), metaClass(groovy.lang.Closure)

**Comment by krlaframboise** [comment]
You're trying to create a device handler by pasting it into the SmartApp screen or visa-versa.

Either that or you didn't click the "RAW" link before copying and either missed some of the code or copied something that wasn't code.

**Comment by kansablankie** [comment]
You are right. Thank you

Best Regards
Belinda

On Jun 23, 2017, at 6:18 PM, Kevin LaFramboise <notifications@github.com<mailto:notifications@github.com>> wrote:


You're trying to create a device handler by pasting it into the SmartApp screen or visa-versa.

Either that or you didn't click the "RAW" link before copying and either missed some of the code or copied something that wasn't code.
