### ISSUE TITLE
Alarm stopped working with device handler since last smartthings update

### ISSUE THREAD

**Issue by BenBurdsall** [krlaframboise/SmartThings#16]
Hi,

I have two zipato multisiren alarms that worked perfectly with your device driver.
There was a firmware update on the EU smartthings hub last week and both stopped working. 
None of the commands worked.

I rebooted the hub this made no difference. 

I switched to the basic aeon siren and it worked, although this only has alarm on and off and no beep command which your one had.

Do other people have the same issue ?

Do you know what I can do to resolve this as your driver was great.

**Comment by krlaframboise** [comment]
This has been fixed in version 1.5.7
