### ISSUE TITLE
Log Does Not Include "Displayed Text" Column From Web-Available Log

### ISSUE THREAD

**Issue by CarlEdman** [krlaframboise/SmartThings#17]
Checking into the [web interface for the SmartThings hub](https://graph.api.smartthings.com/) and looking at the event logs shows a column "Displayed Text."    While that generally only seems to be some sort of more verbose verbal description of the data in the prior columns, in at least once case it is the exclusive source of important data:

My Schlage Front Door lock will generate entries when unlocked by code like this:

Date: 2017-09-21 4:03:21.122 PM EDT 1 hour ago
Source: DEVICE
Type: 
Name: lock
Value: unlocked
User: 
Displayed Text: Front Door was unlocked with code 4

In the SmartThings Simple Event Log that becomes:

09/21/2017 16:03:21 | Front Door | lock | unlocked | unlocked

The information about *who* unlocked the door (or at least whose code was used) gets lost.  That seems a shame.

Any way to fix this?

**Comment by krlaframboise** [comment]
In the Other Options section there's a setting for "Log Event Description" and if it's enabled the app should log the full message.

**Comment by CarlEdman** [comment]
Thanks, that was the first thing I checked, but it was (and always has been) on.  And indeed, the sheet does contain a "Description" column, but that is just a repetition of the previous column, sometimes with slightly different language, not the full text of what is in the "Displayed Text" column in the web view.  For example, in the above case, it just says "unlocked" rather than "Front Door was unlocked with code 4."

**Comment by krlaframboise** [comment]
You're right, all that gets logged to the description column is the value and unit together.

I'm not sure if this is something I want to build in as a setting, but you can make yours log the full description by replacing line 722 with the line below.

`desc: "${event.descriptionText}" ?: ""`

**Comment by CarlEdman** [comment]
Thanks, that worked!  But isn't that is the way it is supposed to work everybody by providing some additional information beyond what is already in the other columns?  Apart from potentially the unit, the description column otherwise is just repetitive.

**Comment by CarlEdman** [comment]
One more thing: Your solution, while an improvement, is not quite perfect.  Consider this event as reported in the SmartThing Events log:

![untitled](https://user-images.githubusercontent.com/705407/30778253-d81e275a-a09e-11e7-9e29-055d58097630.png)

In the Google Drive spreadsheet, this shows up as:
09/23/2017 19:46:20 | Carl's Minimote | button | pushed | {{ linkText }} {{ name }} is {{ value }}

If you look at the description, the actual Event Description requires substitution with some mustache-like syntax from the other values.  Would it be possible for your Logger to log the fully expanded description, rather than the formula with the placeholders?  This is of course something that could be done later in an additional processing step, but I think it would be nicest/easiest as you create the entry because all the variables are already at hand.

**Comment by krlaframboise** [comment]
Are yous seeing that with all your devices or just a few?

**Comment by CarlEdman** [comment]
Just a few.  In particular, I see it with the minimotes and the iPhone presence detector which gets logged with descriptions like "{{ linkText }} has arrived".

**Comment by krlaframboise** [comment]
There's nothing in the SmartThings documentation about tokens for the descriptionText so those device handlers shouldn't be doing that.

I originally wrote this SmartApp for logging raw data which is why the description column logs the value and unit instead of the descriptionText.  If at some point I decide to make the SmartApp log the descriptionText field I'll build in the token replacement, but I don't have time to mess with it right now.

You may want to search the SmartThings forum for a SmartApp called something like Google Sheets Logger because it might provide the flexibility you're looking for.

**Comment by CarlEdman** [comment]
Thanks for all your help.  Just getting the actual description text was the most important thing.  As to the substitutions, I am not surprised this is undocumented, even though more than one manufacturer seems to have gotten the idea that this is ok (and the official Samsung web app seems to interpolate them).

**Comment by krlaframboise** [comment]
If you check the device handler code of all the devices that are doing it you'll most likely find that they were all written by SmartThings...

**Comment by krlaframboise** [comment]
If you update to version 1.4 of the SmartApp you can disable the new "Use Value and Unit for "Description" setting in the "Other Options" section and it will log the descriptionText?

I've also manually implemented the token replacement for it, but since those tokens are undocumented it's possible that I missed some of them.

**Comment by CarlEdman** [comment]
Thanks!  I've installed 1.4 and will let you know if I notice anything amiss in the next few days.
