### ISSUE TITLE
No Bell, chime, or siren.

### ISSUE THREAD

**Issue by aratherlargesheep** [krlaframboise/SmartThings#18]
No bell, chime or siren is available.  The only thing that is available is alarm.  When I try one of the other buttons it says in the log:

> Unable to start chime because alarm is on or pending.

Thank-you!

**Comment by krlaframboise** [comment]
Are you the one that posted this issue to the Dome Siren topic in the SmartThings forum last night?

**Comment by aratherlargesheep** [comment]
No I have only found it now as I am trying to set up for the first time.
On Oct 11, 2017, at 6:13 PM, Kevin LaFramboise <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you the one that posted this issue to the Dome Siren topic in the SmartThings forum last night?

**Comment by krlaframboise** [comment]
I'd rather troubleshoot this issue in one location so please respond on the forum to the questions I asked in the last post of the topic below.

https://community.smartthings.com/t/release-dome-siren-official/75499
