### ISSUE TITLE
Problem creating Web App

### ISSUE THREAD

**Issue by zvanaernum** [krlaframboise/SmartThings#21]
Hello, thank you for creating this app, it seems really cool.

I am having trouble creating the google web app. I was sure to copy and paste the script exactly and I made sure to make the URL accessible to anyone. I have tried it a couple of times and I still get the following when I try to load the URL:

Sorry, unable to open the file at this time.

Please check the address and try again. 

Any suggestions?

Thanks!

**Comment by squeaky369** [comment]
I am having the exact same issue. I've tried with Google Accounts with 2FA on and 2FA off, doesn't matter on the account type or permission settings.

**Comment by zvanaernum** [comment]
Squeaky369, I found that removing /U0 from my URL fixed the problem. Your may have a U1 instead of U0. Try that and see if it works!

**Comment by atitannapolis** [comment]
I installed everything and have had my tp-link Kasa outlets running great for a couple months now.

But suddenly I'm getting this error:

[image1.PNG]


[image4.JPG]

[image3.PNG]


Any thoughts?


Thanks so much

![img_4041](https://user-images.githubusercontent.com/29963758/32997982-019a2bf4-cd65-11e7-9a90-a700aeba4569.PNG)
![img_4043](https://user-images.githubusercontent.com/29963758/32997983-01a59f52-cd65-11e7-9f55-83640fbea80b.PNG)
![img_4044](https://user-images.githubusercontent.com/29963758/32997984-01b2966c-cd65-11e7-8f79-f68a55536ae3.JPG)

**Comment by krlaframboise** [comment]
The images didn't get attached to your post so I can't see the error messages...

**Comment by atitannapolis** [comment]
Whoops. Sorry, updated.

**Comment by krlaframboise** [comment]
I haven't created any DTHs or SmartApps for the TP Link so you need to post that issue to wherever you got that DTH and SmartApp from...

**Comment by atitannapolis** [comment]
Yes, so sorry. Thank you. Wrong thread! I apologize. It's been a long week.
