### ISSUE TITLE
Consider renaming repo to make it easier to identify in update from repo list

### ISSUE THREAD

**Issue by jmaxxz** [krlaframboise/SmartThings#23]
Unique repo names makes it much easier for people to identify your repo from the update from repo drop down. Renaming your repo to `krlaframboise-smartthings` would make it much easier to find in the list.

![image](https://user-images.githubusercontent.com/828153/35310749-89945b74-0078-11e8-886a-0a0002bc5d8e.png)

**Comment by krlaframboise** [comment]
Renaming the repository isn't an option because it would break the SmartThings integration for thousands of users and it would also break a bunch of links on the SmartThings forum and other websites like The Smartest House, Dome, Aeotec, Amazon, and YouTube.

**Comment by jmaxxz** [comment]
@krlaframboise it actually wouldn't, github handles redirects when you rename a repo.

**Comment by jmaxxz** [comment]
https://help.github.com/articles/renaming-a-repository/

>In addition to redirecting web traffic, all git clone, git fetch, or git push operations targeting the previous location will continue to function as if made on the new location.
