### ISSUE TITLE
Any plan to integrate with Flo?

### ISSUE THREAD

**Issue by cihanucar** [krlaframboise/SmartThings#24]
I was wondering if you would be interested in adding Flo to SmartThings.

https://meetflo.com/

Flo is a water monitoring and shut-off system that proactively detects micro-leaks and other vulnerabilities anywhere in your homes water supply, preventing costly damage by giving you the tools to stop damage and better maintain your home.

**Comment by krlaframboise** [comment]
I only write integrations for products that I own, but if you're associated with  Flo Technologies Inc and you're looking for an integration, email me and we can discuss it.  klaframboise@comcast.net
