### ISSUE TITLE
dome siren - smartthings - excessive beeping

### ISSUE THREAD

**Issue by fireheadman** [krlaframboise/SmartThings#25]
Have the siren configured per documentation....
DTH is installed.

When first installed, it worked great.
Over the months it randomly will beep upwards of 8 times when a door is opened.   The default, expected behavior is to beep a single time when open and once more when closed.

Seems to get stuck in a beep mode.... drives us crazy!
If there is anything I can do to provide logs...etc, please let me know.

**Comment by tarostegui** [comment]
Same issue...we've tried multiple solutions and none have worked.

**Comment by krlaframboise** [comment]
If you're using SHM to activate the chime you should switch to Speaker Companion.

**Comment by tarostegui** [comment]
I've done both SHM and CoRE to activate the chime.  I will try Speaker
Companion next to see if I get different results.

Thanks for the feedback.

**Comment by fireheadman** [comment]
Speaker companion is the app of choice I have been using from Day one.   Issue persist using it.  

![image](https://user-images.githubusercontent.com/19847195/38504652-778b9038-3bd2-11e8-85e7-14d0fe00aaf9.png)

**Comment by krlaframboise** [comment]
This isn't something that can be fixed in the DTH...
