### ISSUE TITLE
Ecolink Motion Sensor

### ISSUE THREAD

**Issue by jsarcone** [krlaframboise/SmartThings#26]
I'm using the IDE for the Ecolink Motion Sensor 2.5 Z-wave plus. I"m seeing that this is always in tamper detected from the ST Classic app. However, from the IDE console it show CLEAR. 
battery: 99 %
motion: active
checkInterval: 65100
tamper: clear
lastCheckin: 07/28/2018 12:02:32 AM
However, the TEMPER is organ and not clear according to the code. Please let me know if I'm off base. 

Thanks.

**Comment by krlaframboise** [comment]
After tamper is detected you have to tap the Refresh tile to clear it.

**Comment by jsarcone** [comment]
On iOS Mobile that doesn't seem to work. Android it does work.

**Comment by krlaframboise** [comment]
I haven't seen that problem before so wait until the next iOS mobile app update and let me know if it's still doing it.

**Comment by jsarcone** [comment]
OK thanks. I will try to send a screen shot.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
