### ISSUE TITLE
Siren won't sound if strobe is already on

### ISSUE THREAD

**Issue by pakmans** [krlaframboise/SmartThings#3]
I have a smartapp that turns the strobe on whenever the security system is armed.
When the strobe is on and a both() command is issued (i.e. an intrussion is detected) the alarm doesn't sound.
I have managed to "fix" the problem by adding:

result << zwave.basicV1.basicSet(value: 0x00).format()

to line 379 inside turnOn of current version (1.6) to force an off before any other command.

It works, but I don't love the solution. I'm still trying to fully understand your code in order to make a cleaner solution.

**Comment by krlaframboise** [comment]
Are you saying that the strobe is on the entire time that your system is armed?  If that's the case you must be burning through batteries like crazy.

I've verified the behavior and will have a fix posted shortly.

FYI, when testing the device, make sure you disable the auto off feature.

**Comment by krlaframboise** [comment]
I just released version 1.6.1 which should fix this problem.

**Comment by pakmans** [comment]
I'm concerned about your comment regarding "burning through batteries like crazy".
My siren is connected to the mains power line, so I would assume it shouldn't use the batteries unless there is a power outage. Is there something else I should know?
I thought it could be very useful to have the strobe on whenever the security system is on so that I can visually tell if it is armed or not.. this also prevents me from accidentally setting off the alarm when going out the house when security is still armed.
By the way, thank you for this device handler, it is absolutely fantastic.

**Comment by krlaframboise** [comment]
The GoControl/Linear Siren only runs on batteries, but this device handler works with at least two other sirens.

Which siren are you using?

**Comment by pakmans** [comment]
Strange... I bought the GoControl/Linear WA105DBZ-1 Siren which _does_ include a power cord.
Mabye it is a newer model?
Here is what I have:

https://www.amazon.com/gp/product/B00MNYSEKY/ref=oh_aui_detailpage_o00_s01?ie=UTF8&psc=1

**Comment by krlaframboise** [comment]
It turns out there are two versions of this siren that have the same model number, but different manuals.

There's a kit that comes with the siren, a motion sensor, and 3 contact sensors and it doesn't provide a power cable or mention anything about it being powered in the manual.

I've opened mine a couple of times and didn't see a place to plug in a power cord, but I wasn't looking for one either so I'll take a closer look tonight.

**Comment by krlaframboise** [comment]
The Linear manual that came with my siren was labeled WA105DBZ, but when I opened the device to check if it had a spot for a power cable, I found a label with the model #: ZM1601US-3 and it's definitely only runs on batteries.

Thanks for letting me know about the bug and for letting me know that there's a powered version of this siren.
