### ISSUE TITLE
Ecolink motion sensor sending multiple events to handler with V3 HUB

### ISSUE THREAD

**Issue by tryagain123** [krlaframboise/SmartThings#34]
I'm using the latest 2.5 plus motion sensors from ecolink with the V3 hub. My smartapp callback  is getting to 2 'active' or 2 'inactive' to the callback  handler which I can't filter out.   Its only a problem with the 2.5 plus with V3 hub.   2.5 Plus with V2 is not a problem and the older sensors work fine with the V3 hub.

I've tried state variables (can't use atomicState since I have extensive state code done).   I like the sensors because the battery life is excellent.

Any ideas?  

Thx!

**Comment by jds13** [comment]
I have the "Eco Z-Wave Plus Motion & Light Sensor", UPC 862294000322, bought on eBay. It works fine with Kevin LaFramboise's "Dome Motion Sensor v1.2.1" device handler. SmartThings V2, so this may be irrelevant.

**Comment by krlaframboise** [comment]
The device doesn't have any configuration parameters so you're better off using the built-in handler so that it executes locally.

**Comment by tryagain123** [comment]
I spoke to Ecolink support and asked them if they could provide there own handler for ST.  I attached the provided ST 2.5 Plus handler.  It works fine.  The downside is that this handler is for the ST Motion sensor with Temperature support.   We removed temp authorization as a work around.
