### ISSUE TITLE
Ecolink door/window sensor with ST3 hub configured chime repeats twice

### ISSUE THREAD

**Issue by spartan77777** [krlaframboise/SmartThings#36]
Configured Dome DMS01 on ST3 to chime once as a custom rule when ecolink  (DWZWAVE2.5-ECO)  zwave plus door sensor gets open state.  Defined it as a custom message "bell1".  It gets triggered successfully however instead of configured one time chime it repeats twice each time the door opened.

**Comment by krlaframboise** [comment]
This is a communication problem between SmartThings and the Siren which has something to do with it being a beaming device and taking too long to acknowledge the first command sent to it causing SmartThings to resend the command multiple times.

The Neo Siren has the same problem and I just discovered a workaround that reduces the frequency of that happening, but it causes the siren to take 2 seconds longer to start playing the sound.

I haven't tested the workaround with the Dome Siren, but if that 2 second delay doesn't bother you and you want to try the workaround, make the change below and let me know if it makes a difference.  

**On line 826, replace this block of code:**

```
def cmds = [
		indicatorSetCmd(sound),
		indicatorGetCmd()
	]
```

**With This:**

```
def cmds = [
		indicatorSetCmd(0),
		"delay 2000",
		indicatorSetCmd(sound),
		indicatorGetCmd()
	]
```

**Comment by spartan77777** [comment]
Implemented the workaround remotely to Dome siren code.  Will test at location tomorrow and update. Thanks.

**Comment by spartan77777** [comment]
No luck.  The double chime continues even after the change.  I can see in the notification of ST, the open even doubles up every time it occurs.  Makes me wonder if there is a custom DH for this.  ST identified correctly but assigned as generic zwave sensor...

**Comment by krlaframboise** [comment]
Does the siren show duplicate play commands in live logging?
