### ISSUE TITLE
Simple Event Logger Error 404

### ISSUE THREAD

**Issue by pdino** [krlaframboise/SmartThings#38]
Good Morning, I just installed your app. I'm not getting any data in the spreadsheet and when I check the live logging in the Smartthings IDE I get 
	Unexpected response from Google Sheets Web App: Failed with status code 404
Any suggestions?

Thanks,

Paul

**Comment by krlaframboise** [comment]
It sounds like the url to the google sheet you entered into the settings is incorrect so it's returning a page not found error.

**Comment by pdino** [comment]
That was my first thought but I do see the version when I browse to it directly.

**Comment by krlaframboise** [comment]
Double check that your pasting the correct portion of the url into the google sheets url field and watch live logging when you save because it should warn you of any problems.
