### ISSUE TITLE
Hank RGB error on new Smartthings app

### ISSUE THREAD

**Issue by loganbest** [krlaframboise/SmartThings#45]
ST Classic works fine when changing colours, but when I try on the new ST app I see this error message in the logs.

```
groovy.lang.MissingMethodException: No signature of method: script_dth_3e9cf2977a2cfbbb838c3af2d154ffce1bf76b6e935140cf7dda9ccdaeb1a1b2.huesatToRGB() is applicable for argument types: (java.lang.Double, java.lang.Integer) values: [5.833333333333333, 74] @line 254 (setColor)
```

Consequently, This error also happens when trying to change the colour via Home Assistant's Smartthings integration.

I am using the most up2date device handler you have published on GH.

**Comment by krlaframboise** [comment]
I just posted a new version that should solve the problem, but let me know if it doesn't.
