### ISSUE TITLE
Is there App Code to go with your zooz power switch  & double plug drivers?

### ISSUE THREAD

**Issue by ron7777777** [krlaframboise/SmartThings#50]
Please forgive my ignorance in advance. I am new to habitat and smartthings and wish to generate a consolidated utilities report for energy usage/cost across multiple zoos power switch and double plug devices and your code looks like an excellent start. 

I have imported zooz-double-plug.groovy & zooz-power-switch.groovy into Habitat(main menu)->Advanced <> Drivers Code without issue.

Do you have any ajoining app code which I can import  into Habitat(main menu)->Advanced <> Apps Code to pair with these two drivers to get things going?

**Comment by krlaframboise** [comment]
This isn't the right place to discuss this so send me a private message @krlaframboise on either the Hubitat or SmartThings forum.
