### ISSUE TITLE
Duplicate log entries

### ISSUE THREAD

**Issue by zvolensky** [krlaframboise/SmartThings#52]
I set things up on Nov 25.   Two days later, I noticed that some events have duplicate entries.   See attached.

![2020-11-28 09_36_57-SmartThings Event Log - Google Sheets](https://user-images.githubusercontent.com/56326480/100518111-78014200-315d-11eb-89c7-3bb92dce3ae8.jpg)

Is there a way to eliminate the duplicates?

**Comment by krlaframboise** [comment]
This SmartApp is no longer supported, but this is the first time I've seen that issue reported so if you post the question to the SmartApp's forum topic then someone might be able to help you figure out what's causing it.
