### ISSUE TITLE
Any advice? Not sure if DTH related?

### ISSUE THREAD

**Issue by dmurchie** [krlaframboise/SmartThings#53]
In the last week or so, weird thing going on - never seen before with *any* devices in my 6-7 years on Smarthings:

Turn HS-200 switch on with paddle tap up, switch turns on and then it turns itself off (sometimes with delay). The only warnings I see in live logging are all related to the HS 200's using this DTH (see below - all of these device IDs are HS switches).

Any ideas?

Thanks,
David

`a6117f43-a308-40c6-90a2-1f4ba64ad0e3  6:05:35 PM: warn unable to parse targetValue from 'zw device: 15, command: 2603, payload: 63 '`
`610cc1a7-9f1f-4929-9563-4a8b4a25581e  6:05:35 PM: warn unable to parse targetValue from 'zw device: 17, command: 2603, payload: 00 '`
`c5fd1ad4-94cb-4ad4-b993-221c0bf579af  6:05:35 PM: warn unable to parse targetValue from 'zw device: 16, command: 2603, payload: 63 '`
`c5fd1ad4-94cb-4ad4-b993-221c0bf579af  6:05:34 PM: warn unable to parse targetValue from 'zw device: 16, command: 2603, payload: 63 '`
`610cc1a7-9f1f-4929-9563-4a8b4a25581e  6:05:34 PM: warn unable to parse targetValue from 'zw device: 17, command: 2603, payload: 00 '`
`c5fd1ad4-94cb-4ad4-b993-221c0bf579af  6:05:34 PM: warn unable to parse targetValue from 'zw device: 16, command: 2603, payload: 63 '`
`610cc1a7-9f1f-4929-9563-4a8b4a25581e  6:05:34 PM: warn unable to parse targetValue from 'zw device: 17, command: 2603, payload: 00 '`

**Comment by krlaframboise** [comment]
Those messages are from my HS-WD200 DTH which is meant for the dimmer so if you have the switch then you need to be using my HS-WS200 handler.

**Comment by dmurchie** [comment]
I should have been more precise - there are three WD-200s and one WS-200, each set to the appropriate handler.

As to not take up too much of your time, could you tell me - in general - what “unable to parse targetValue from...” indicates (is it the handler can’t parse the value? Or is it ST?) and what the command and payload values represent?

I googled this a bit and haven’t come up with  a straightforward answer.

**Comment by krlaframboise** [comment]
The WD-200+ supports at least version 4 of the Switch Multilevel command class which has a targetValue field in the reports it sends to the hub.  SmartThings doesn't support that version so my DTH is parsing it out of the raw hex string, but it's throwing an exception which is why you're seeing that generic message.

The reason it's throwing an exception is that your device isn't sending the targetValue which shouldn't be possible.

Open the device in the IDE and post what's shown next to Raw Description so I can see your device's firmware information..

**Comment by dmurchie** [comment]
As I said didn’t want to take up your time - of course my problems are all ST problem

**Comment by dmurchie** [comment]
Sure didn’t want to take up any of your time with this - turns out it’s all ST platform problems (automations and scenes suddenly gone wacky all by themselves). Nothing to do with your handlers. I should have assumed it was the platform (which is a bummer - getting to be a regular thing). 

Sorry about that...
