### ISSUE TITLE
Zuno Smartthing  Device Handler 

### ISSUE THREAD

**Issue by SpaceManCoder** [krlaframboise/SmartThings#55]
Hello Kevin, I need some help to develop a Device Handler for ZUNO.   My project is to control 8 relays and display a temperature for my private pool. Arduino code isn't a problem for me. But I didn't understand how to create a multi-tile for mobile with the new Smartthings like you done with the zooz multi-relay.   Let me know if you're willing to help me.

**Comment by krlaframboise** [comment]
Send me a PM on the SmartThings Forum.
