### ISSUE TITLE
Zooz Scene Controller - LED Controller based on Device State

### ISSUE THREAD

**Issue by NickSchweitzer** [krlaframboise/SmartThings#58]
Right now, the colors are statically assigned. It would be great if the color of the LED for a button could be changed based on the state of a device. For instance, if the LED could be red when my garage door is open.

**Comment by HamZhbbbb** [comment]
أحمر**** #57

**Comment by krlaframboise** [comment]
The handle already supports that...

Setup a routine with "IF" garage door opens "THEN" Set Color of the corresponding button.  You'd need a second routine to change it back when the door closes.
