### ISSUE TITLE
Using Zen72 S2 in WebCore

### ISSUE THREAD

**Issue by CoryAlbrecht** [krlaframboise/SmartThings#61]
Do you have or know of any examples for using this DTH in WebCore?

In the SmartThings IDE I can see the `button` parameter changing to things like `up_3x`, `down_2x`, etc… as I tap the paddle, but I just cannot seem to figure out how to check that in WebCore.

Any help would be appreciated.

**Comment by krlaframboise** [comment]
To use those actions you need to setup the trigger like below.  

The confusing part is that after selecting "Expression" near the bottom you have to type the button action wrapped with quotes in the box below it.

![image](https://user-images.githubusercontent.com/16527141/160697479-967e69ce-64c3-4a8e-84e8-faf888586825.png)

**Comment by davejake** [comment]
YES! That was my problem, I was neglecting the "Quotation Marks".   now it works!!! Thanks
