### ISSUE TITLE
Error when creating app

### ISSUE THREAD

**Issue by Gotfrogs** [krlaframboise/SmartThings#7]
Thanks for creating this app. I am new to the process of loading apps for SmartThings but get the following error when trying to create/publish your app for my use:

No signature of method: script14765916065191527942943.metadata() is applicable for argument types: (script14765916065191527942943$_run_closure1) values: [script14765916065191527942943$_run_closure1@560dd057] Possible solutions: getMetadata(), getState(), setState(java.lang.Object), metaClass(groovy.lang.Closure)

**Comment by krlaframboise** [comment]
Make sure you're clicking raw before copying the code and you're pasting the code into the My SmartApps section and not my device types.

**Comment by Sanitys** [comment]
This still does not work even with RAW.

No signature of method: script1482558329397386385218.metadata() is applicable for argument types: (script1482558329397386385218$_run_closure1) values: [script1482558329397386385218$_run_closure1@31de2212] Possible solutions: getMetadata(), getState(), setState(java.lang.Object), metaClass(groovy.lang.Closure)
